### ISSUE TITLE
UX/UI: Empty message modal on reload

### ISSUE THREAD

**Issue by dixflatlinr** [sakurity/securelogin#9]
cobased.com:

Under MacOS/Safari, with an installed SecureLogin app, and logged in. Whenever I click on "Change securelogin" and press cancel - and/or allow and later on close the securelogin app -, doing a reload pops up an empty message modal with a close button in the browser.

**Comment by homakov** [comment]
Got it, it happens because the pulling request fails but for some reason readyState jumps right to 4 (successful response) which alerts empty body. 

Actually it's only relevant to Playground because normal sites have better handling of responses. fixed

`      if(cb && x.response.length > 1) cb( (x.response) )`
